# coding: utf-8

"""
    Galaxy 3.2 API (wip)

    Galaxy 3.2 API (wip)  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.models.collection_version_link import CollectionVersionLink  # noqa: E501
from openapi_client.rest import ApiException


class TestCollectionVersionLink(unittest.TestCase):
    """CollectionVersionLink unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCollectionVersionLink(self):
        """Test CollectionVersionLink"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openapi_client.models.collection_version_link.CollectionVersionLink()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
