# coding: utf-8

"""
    Galaxy 3.2 API (wip)

    Galaxy 3.2 API (wip)  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.collection_imports_api import CollectionImportsApi  # noqa: E501
from openapi_client.rest import ApiException


class TestCollectionImportsApi(unittest.TestCase):
    """CollectionImportsApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.collection_imports_api.CollectionImportsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_collection_import_by_id(self):
        """Test case for get_collection_import_by_id

        Get a Collection-Import (import task) by id  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
