# coding: utf-8

"""
    Galaxy 3.2 API (wip)

    Galaxy 3.2 API (wip)  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.download_api import DownloadApi  # noqa: E501
from openapi_client.rest import ApiException


class TestDownloadApi(unittest.TestCase):
    """DownloadApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.download_api.DownloadApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_download_artifact_by_filename(self):
        """Test case for download_artifact_by_filename

        Download the collection artifact  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
