# coding: utf-8

"""
    Galaxy 3.2 API (wip)

    Galaxy 3.2 API (wip)  # noqa: E501

    The version of the OpenAPI document: 1.1.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.models.body4 import Body4  # noqa: E501
from openapi_client.rest import ApiException


class TestBody4(unittest.TestCase):
    """Body4 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBody4(self):
        """Test Body4"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openapi_client.models.body4.Body4()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
