# coding: utf-8

"""
    Galaxy 3.2 API (wip)

    Galaxy 3.2 API (wip)  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.users_api import UsersApi  # noqa: E501
from openapi_client.rest import ApiException


class TestUsersApi(unittest.TestCase):
    """UsersApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.users_api.UsersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_user_by_id(self):
        """Test case for get_user_by_id

        Get an User by id  # noqa: E501
        """
        pass

    def test_list_users(self):
        """Test case for list_users

        Get a list of Users  # noqa: E501
        """
        pass

    def test_patch_user_by_id(self):
        """Test case for patch_user_by_id

        Patch/update an User by id  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
