# coding: utf-8

"""
    Galaxy 3.2 API (wip)

    Galaxy 3.2 API (wip)  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.search_api import SearchApi  # noqa: E501
from openapi_client.rest import ApiException


class TestSearchApi(unittest.TestCase):
    """SearchApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.search_api.SearchApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_api_v1_search(self):
        """Test case for get_api_v1_search

        Get info about the v1 search API  # noqa: E501
        """
        pass

    def test_list_content_by_search(self):
        """Test case for list_content_by_search

        Get a list of Contents by searching  # noqa: E501
        """
        pass

    def test_list_role_by_search(self):
        """Test case for list_role_by_search

        """
        pass

    def test_list_tag_by_search(self):
        """Test case for list_tag_by_search

        Get a list of Tags by searching  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
