# coding: utf-8

"""
    Galaxy 3.2 API (wip)

    Galaxy 3.2 API (wip)  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.models.collection_version_detail_metadata import CollectionVersionDetailMetadata  # noqa: E501
from openapi_client.rest import ApiException


class TestCollectionVersionDetailMetadata(unittest.TestCase):
    """CollectionVersionDetailMetadata unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCollectionVersionDetailMetadata(self):
        """Test CollectionVersionDetailMetadata"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openapi_client.models.collection_version_detail_metadata.CollectionVersionDetailMetadata()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
