# coding: utf-8

"""
    Galaxy 3.2 API (wip)

    Galaxy 3.2 API (wip)  # noqa: E501

    The version of the OpenAPI document: 1.1.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.models.body6 import Body6  # noqa: E501
from openapi_client.rest import ApiException


class TestBody6(unittest.TestCase):
    """Body6 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBody6(self):
        """Test Body6"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openapi_client.models.body6.Body6()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
