export * from './collectionImports.service';
import { CollectionImportsService } from './collectionImports.service';
export * from './collectionVersions.service';
import { CollectionVersionsService } from './collectionVersions.service';
export * from './collections.service';
import { CollectionsService } from './collections.service';
export * from './download.service';
import { DownloadService } from './download.service';
export * from './internal.service';
import { InternalService } from './internal.service';
export * from './introspection.service';
import { IntrospectionService } from './introspection.service';
export * from './me.service';
import { MeService } from './me.service';
export * from './namespaces.service';
import { NamespacesService } from './namespaces.service';
export * from './notifications.service';
import { NotificationsService } from './notifications.service';
export * from './search.service';
import { SearchService } from './search.service';
export * from './tags.service';
import { TagsService } from './tags.service';
export * from './users.service';
import { UsersService } from './users.service';
export * from './v1.service';
import { V1Service } from './v1.service';
export * from './v2.service';
import { V2Service } from './v2.service';
export const APIS = [CollectionImportsService, CollectionVersionsService, CollectionsService, DownloadService, InternalService, IntrospectionService, MeService, NamespacesService, NotificationsService, SearchService, TagsService, UsersService, V1Service, V2Service];
