/**
 * Galaxy 3.2 API (wip)
 * Galaxy 3.2 API (wip)
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Body6 { 
    avatarUrl?: string;
    dateJoined?: Date;
    fullName?: string;
    /**
     * Required. 30 characters or fewer. Letters, numbers and @/./+/-/_ characters
     */
    username?: string;
}