/**
 * Galaxy 3.2 API (wip)
 * Galaxy 3.2 API (wip)
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface InlineResponse2002Namespace { 
    active?: boolean;
    avatarUrl?: string;
    company?: string;
    readonly created?: Date;
    description?: string;
    email?: string;
    htmlUrl?: string;
    readonly id?: number;
    isVendor?: boolean;
    location?: string;
    readonly modified?: Date;
    name: string;
    owners: Array<number>;
}