/**
 * Galaxy 3.2 API (wip)
 * Galaxy 3.2 API (wip)
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface InlineResponse2001 { 
    readonly active?: string;
    collectionsFollowed?: Array<number>;
    /**
     * Timestamp when this user preferences was created.
     */
    readonly created?: string;
    /**
     * Timestamp when this user preferences was last modified.
     */
    readonly modified?: string;
    namespacesFollowed?: Array<number>;
    preferences: any;
    /**
     * Data structure with URLs of related resources.
     */
    readonly related?: string;
    repositoriesFollowed?: Array<number>;
    /**
     * Data structure with name/description for related resources.
     */
    readonly summaryFields?: string;
    /**
     * URL for this user preferences.
     */
    readonly url?: string;
}