/**
 * Galaxy 3.2 API (wip)
 * Galaxy 3.2 API (wip)
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */import { InlineResponse20015Error } from './inlineResponse20015Error';
import { InlineResponse20015Messages } from './inlineResponse20015Messages';


export interface InlineResponse20015 { 
    error: InlineResponse20015Error;
    finishedAt: Date;
    id: number;
    readonly importedVersion?: string;
    jobId: string;
    lintRecords: any;
    messages: Array<InlineResponse20015Messages>;
    name: string;
    namespace: string;
    startedAt: Date;
    state: string;
    version: string;
}