/**
 * Galaxy 3.2 API (wip)
 * Galaxy 3.2 API (wip)
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */import { BigDecimal } from './bigDecimal';
import { InlineResponse2002LatestVersion } from './inlineResponse2002LatestVersion';
import { InlineResponse2002Namespace } from './inlineResponse2002Namespace';


export interface InlineResponse2002 { 
    communityScore?: BigDecimal;
    communitySurveyCount?: number;
    readonly created?: Date;
    deprecated?: boolean;
    downloadCount?: number;
    readonly id?: number;
    latestVersion: InlineResponse2002LatestVersion;
    readonly modified?: Date;
    name: string;
    namespace?: InlineResponse2002Namespace;
}