/**
 * Galaxy 3.2 API (wip)
 * Galaxy 3.2 API (wip)
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */import { BigDecimal } from './bigDecimal';


export interface InlineResponse2004LatestVersion { 
    contents: any;
    readonly created?: Date;
    metadata: any;
    readonly modified?: Date;
    readonly pk?: number;
    qualityScore?: BigDecimal;
    readmeHtml?: string;
    version: string;
}