/**
 * Galaxy 3.2 API (wip)
 * Galaxy 3.2 API (wip)
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface InlineResponse2006 { 
    readonly active?: string;
    readonly authenticated?: string;
    avatarUrl?: string;
    /**
     * Timestamp when this user was created.
     */
    readonly created?: string;
    dateJoined?: Date;
    fullName?: string;
    /**
     * Database ID for this user.
     */
    readonly id?: number;
    /**
     * Timestamp when this user was last modified.
     */
    readonly modified?: string;
    readonly primaryEmail?: string;
    /**
     * Data structure with URLs of related resources.
     */
    readonly related?: string;
    readonly staff?: string;
    /**
     * Data structure with name/description for related resources.
     */
    readonly summaryFields?: string;
    /**
     * URL for this user.
     */
    readonly url?: string;
    /**
     * Required. 30 characters or fewer. Letters, numbers and @/./+/-/_ characters
     */
    username: string;
}