# coding: utf-8

"""
    Galaxy 3.2 API (wip)

    Galaxy 3.2 API (wip)  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class CollectionImportLintRecord(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'code': 'str',
        'type': 'str',
        'message': 'str',
        'severity': 'int',
        'score_type': 'str'
    }

    attribute_map = {
        'code': 'code',
        'type': 'type',
        'message': 'message',
        'severity': 'severity',
        'score_type': 'score_type'
    }

    def __init__(self, code=None, type=None, message=None, severity=None, score_type=None):  # noqa: E501
        """CollectionImportLintRecord - a model defined in OpenAPI"""  # noqa: E501

        self._code = None
        self._type = None
        self._message = None
        self._severity = None
        self._score_type = None
        self.discriminator = None

        if code is not None:
            self.code = code
        if type is not None:
            self.type = type
        if message is not None:
            self.message = message
        if severity is not None:
            self.severity = severity
        self.score_type = score_type

    @property
    def code(self):
        """Gets the code of this CollectionImportLintRecord.  # noqa: E501


        :return: The code of this CollectionImportLintRecord.  # noqa: E501
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code):
        """Sets the code of this CollectionImportLintRecord.


        :param code: The code of this CollectionImportLintRecord.  # noqa: E501
        :type: str
        """

        self._code = code

    @property
    def type(self):
        """Gets the type of this CollectionImportLintRecord.  # noqa: E501


        :return: The type of this CollectionImportLintRecord.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this CollectionImportLintRecord.


        :param type: The type of this CollectionImportLintRecord.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def message(self):
        """Gets the message of this CollectionImportLintRecord.  # noqa: E501


        :return: The message of this CollectionImportLintRecord.  # noqa: E501
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this CollectionImportLintRecord.


        :param message: The message of this CollectionImportLintRecord.  # noqa: E501
        :type: str
        """

        self._message = message

    @property
    def severity(self):
        """Gets the severity of this CollectionImportLintRecord.  # noqa: E501


        :return: The severity of this CollectionImportLintRecord.  # noqa: E501
        :rtype: int
        """
        return self._severity

    @severity.setter
    def severity(self, severity):
        """Sets the severity of this CollectionImportLintRecord.


        :param severity: The severity of this CollectionImportLintRecord.  # noqa: E501
        :type: int
        """

        self._severity = severity

    @property
    def score_type(self):
        """Gets the score_type of this CollectionImportLintRecord.  # noqa: E501


        :return: The score_type of this CollectionImportLintRecord.  # noqa: E501
        :rtype: str
        """
        return self._score_type

    @score_type.setter
    def score_type(self, score_type):
        """Sets the score_type of this CollectionImportLintRecord.


        :param score_type: The score_type of this CollectionImportLintRecord.  # noqa: E501
        :type: str
        """

        self._score_type = score_type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CollectionImportLintRecord):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
