# coding: utf-8

"""
    Galaxy 3.2 API (wip)

    Galaxy 3.2 API (wip)  # noqa: E501

    The version of the OpenAPI document: 1.1.1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class Collection(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'latest_version': 'CollectionLatestVersion',
        'created': 'str',
        'deprecated': 'bool',
        'name': 'str',
        'namespace': 'CollectionNamespace',
        'modified': 'str',
        'id': 'int',
        'href': 'str',
        'versions_url': 'str'
    }

    attribute_map = {
        'latest_version': 'latest_version',
        'created': 'created',
        'deprecated': 'deprecated',
        'name': 'name',
        'namespace': 'namespace',
        'modified': 'modified',
        'id': 'id',
        'href': 'href',
        'versions_url': 'versions_url'
    }

    def __init__(self, latest_version=None, created=None, deprecated=None, name=None, namespace=None, modified=None, id=None, href=None, versions_url=None):  # noqa: E501
        """Collection - a model defined in OpenAPI"""  # noqa: E501

        self._latest_version = None
        self._created = None
        self._deprecated = None
        self._name = None
        self._namespace = None
        self._modified = None
        self._id = None
        self._href = None
        self._versions_url = None
        self.discriminator = None

        if latest_version is not None:
            self.latest_version = latest_version
        if created is not None:
            self.created = created
        if deprecated is not None:
            self.deprecated = deprecated
        if name is not None:
            self.name = name
        if namespace is not None:
            self.namespace = namespace
        if modified is not None:
            self.modified = modified
        if id is not None:
            self.id = id
        if href is not None:
            self.href = href
        if versions_url is not None:
            self.versions_url = versions_url

    @property
    def latest_version(self):
        """Gets the latest_version of this Collection.  # noqa: E501


        :return: The latest_version of this Collection.  # noqa: E501
        :rtype: CollectionLatestVersion
        """
        return self._latest_version

    @latest_version.setter
    def latest_version(self, latest_version):
        """Sets the latest_version of this Collection.


        :param latest_version: The latest_version of this Collection.  # noqa: E501
        :type: CollectionLatestVersion
        """

        self._latest_version = latest_version

    @property
    def created(self):
        """Gets the created of this Collection.  # noqa: E501


        :return: The created of this Collection.  # noqa: E501
        :rtype: str
        """
        return self._created

    @created.setter
    def created(self, created):
        """Sets the created of this Collection.


        :param created: The created of this Collection.  # noqa: E501
        :type: str
        """

        self._created = created

    @property
    def deprecated(self):
        """Gets the deprecated of this Collection.  # noqa: E501


        :return: The deprecated of this Collection.  # noqa: E501
        :rtype: bool
        """
        return self._deprecated

    @deprecated.setter
    def deprecated(self, deprecated):
        """Sets the deprecated of this Collection.


        :param deprecated: The deprecated of this Collection.  # noqa: E501
        :type: bool
        """

        self._deprecated = deprecated

    @property
    def name(self):
        """Gets the name of this Collection.  # noqa: E501


        :return: The name of this Collection.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Collection.


        :param name: The name of this Collection.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def namespace(self):
        """Gets the namespace of this Collection.  # noqa: E501


        :return: The namespace of this Collection.  # noqa: E501
        :rtype: CollectionNamespace
        """
        return self._namespace

    @namespace.setter
    def namespace(self, namespace):
        """Sets the namespace of this Collection.


        :param namespace: The namespace of this Collection.  # noqa: E501
        :type: CollectionNamespace
        """

        self._namespace = namespace

    @property
    def modified(self):
        """Gets the modified of this Collection.  # noqa: E501


        :return: The modified of this Collection.  # noqa: E501
        :rtype: str
        """
        return self._modified

    @modified.setter
    def modified(self, modified):
        """Sets the modified of this Collection.


        :param modified: The modified of this Collection.  # noqa: E501
        :type: str
        """

        self._modified = modified

    @property
    def id(self):
        """Gets the id of this Collection.  # noqa: E501


        :return: The id of this Collection.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Collection.


        :param id: The id of this Collection.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def href(self):
        """Gets the href of this Collection.  # noqa: E501


        :return: The href of this Collection.  # noqa: E501
        :rtype: str
        """
        return self._href

    @href.setter
    def href(self, href):
        """Sets the href of this Collection.


        :param href: The href of this Collection.  # noqa: E501
        :type: str
        """

        self._href = href

    @property
    def versions_url(self):
        """Gets the versions_url of this Collection.  # noqa: E501


        :return: The versions_url of this Collection.  # noqa: E501
        :rtype: str
        """
        return self._versions_url

    @versions_url.setter
    def versions_url(self, versions_url):
        """Sets the versions_url of this Collection.


        :param versions_url: The versions_url of this Collection.  # noqa: E501
        :type: str
        """

        self._versions_url = versions_url

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Collection):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
