# coding: utf-8

"""
    Galaxy 3.2 API (wip)

    Galaxy 3.2 API (wip)  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class ContentAllOf(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'company': 'str',
        'description': 'str',
        'download_count': 'str',
        'download_rank': 'float',
        'imported': 'datetime',
        'is_valid': 'bool',
        'license': 'str',
        'min_ansible_version': 'str',
        'name': 'str',
        'relevance': 'float',
        'role_type': 'str',
        'search_rank': 'float',
        'travis_status_url': 'str',
        'username': 'str'
    }

    attribute_map = {
        'company': 'company',
        'description': 'description',
        'download_count': 'download_count',
        'download_rank': 'download_rank',
        'imported': 'imported',
        'is_valid': 'is_valid',
        'license': 'license',
        'min_ansible_version': 'min_ansible_version',
        'name': 'name',
        'relevance': 'relevance',
        'role_type': 'role_type',
        'search_rank': 'search_rank',
        'travis_status_url': 'travis_status_url',
        'username': 'username'
    }

    def __init__(self, company=None, description=None, download_count=None, download_rank=None, imported=None, is_valid=None, license=None, min_ansible_version=None, name=None, relevance=None, role_type=None, search_rank=None, travis_status_url=None, username=None):  # noqa: E501
        """ContentAllOf - a model defined in OpenAPI"""  # noqa: E501

        self._company = None
        self._description = None
        self._download_count = None
        self._download_rank = None
        self._imported = None
        self._is_valid = None
        self._license = None
        self._min_ansible_version = None
        self._name = None
        self._relevance = None
        self._role_type = None
        self._search_rank = None
        self._travis_status_url = None
        self._username = None
        self.discriminator = None

        self.company = company
        if description is not None:
            self.description = description
        if download_count is not None:
            self.download_count = download_count
        self.download_rank = download_rank
        self.imported = imported
        if is_valid is not None:
            self.is_valid = is_valid
        if license is not None:
            self.license = license
        self.min_ansible_version = min_ansible_version
        self.name = name
        self.relevance = relevance
        if role_type is not None:
            self.role_type = role_type
        self.search_rank = search_rank
        if travis_status_url is not None:
            self.travis_status_url = travis_status_url
        if username is not None:
            self.username = username

    @property
    def company(self):
        """Gets the company of this ContentAllOf.  # noqa: E501


        :return: The company of this ContentAllOf.  # noqa: E501
        :rtype: str
        """
        return self._company

    @company.setter
    def company(self, company):
        """Sets the company of this ContentAllOf.


        :param company: The company of this ContentAllOf.  # noqa: E501
        :type: str
        """
        if company is not None and len(company) > 50:
            raise ValueError("Invalid value for `company`, length must be less than or equal to `50`")  # noqa: E501

        self._company = company

    @property
    def description(self):
        """Gets the description of this ContentAllOf.  # noqa: E501


        :return: The description of this ContentAllOf.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this ContentAllOf.


        :param description: The description of this ContentAllOf.  # noqa: E501
        :type: str
        """
        if description is not None and len(description) > 255:
            raise ValueError("Invalid value for `description`, length must be less than or equal to `255`")  # noqa: E501

        self._description = description

    @property
    def download_count(self):
        """Gets the download_count of this ContentAllOf.  # noqa: E501


        :return: The download_count of this ContentAllOf.  # noqa: E501
        :rtype: str
        """
        return self._download_count

    @download_count.setter
    def download_count(self, download_count):
        """Sets the download_count of this ContentAllOf.


        :param download_count: The download_count of this ContentAllOf.  # noqa: E501
        :type: str
        """

        self._download_count = download_count

    @property
    def download_rank(self):
        """Gets the download_rank of this ContentAllOf.  # noqa: E501


        :return: The download_rank of this ContentAllOf.  # noqa: E501
        :rtype: float
        """
        return self._download_rank

    @download_rank.setter
    def download_rank(self, download_rank):
        """Sets the download_rank of this ContentAllOf.


        :param download_rank: The download_rank of this ContentAllOf.  # noqa: E501
        :type: float
        """
        if download_rank is None:
            raise ValueError("Invalid value for `download_rank`, must not be `None`")  # noqa: E501

        self._download_rank = download_rank

    @property
    def imported(self):
        """Gets the imported of this ContentAllOf.  # noqa: E501


        :return: The imported of this ContentAllOf.  # noqa: E501
        :rtype: datetime
        """
        return self._imported

    @imported.setter
    def imported(self, imported):
        """Sets the imported of this ContentAllOf.


        :param imported: The imported of this ContentAllOf.  # noqa: E501
        :type: datetime
        """

        self._imported = imported

    @property
    def is_valid(self):
        """Gets the is_valid of this ContentAllOf.  # noqa: E501


        :return: The is_valid of this ContentAllOf.  # noqa: E501
        :rtype: bool
        """
        return self._is_valid

    @is_valid.setter
    def is_valid(self, is_valid):
        """Sets the is_valid of this ContentAllOf.


        :param is_valid: The is_valid of this ContentAllOf.  # noqa: E501
        :type: bool
        """

        self._is_valid = is_valid

    @property
    def license(self):
        """Gets the license of this ContentAllOf.  # noqa: E501


        :return: The license of this ContentAllOf.  # noqa: E501
        :rtype: str
        """
        return self._license

    @license.setter
    def license(self, license):
        """Sets the license of this ContentAllOf.


        :param license: The license of this ContentAllOf.  # noqa: E501
        :type: str
        """
        if license is not None and len(license) > 50:
            raise ValueError("Invalid value for `license`, length must be less than or equal to `50`")  # noqa: E501

        self._license = license

    @property
    def min_ansible_version(self):
        """Gets the min_ansible_version of this ContentAllOf.  # noqa: E501


        :return: The min_ansible_version of this ContentAllOf.  # noqa: E501
        :rtype: str
        """
        return self._min_ansible_version

    @min_ansible_version.setter
    def min_ansible_version(self, min_ansible_version):
        """Sets the min_ansible_version of this ContentAllOf.


        :param min_ansible_version: The min_ansible_version of this ContentAllOf.  # noqa: E501
        :type: str
        """
        if min_ansible_version is not None and len(min_ansible_version) > 10:
            raise ValueError("Invalid value for `min_ansible_version`, length must be less than or equal to `10`")  # noqa: E501

        self._min_ansible_version = min_ansible_version

    @property
    def name(self):
        """Gets the name of this ContentAllOf.  # noqa: E501


        :return: The name of this ContentAllOf.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ContentAllOf.


        :param name: The name of this ContentAllOf.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501
        if name is not None and len(name) > 512:
            raise ValueError("Invalid value for `name`, length must be less than or equal to `512`")  # noqa: E501

        self._name = name

    @property
    def relevance(self):
        """Gets the relevance of this ContentAllOf.  # noqa: E501


        :return: The relevance of this ContentAllOf.  # noqa: E501
        :rtype: float
        """
        return self._relevance

    @relevance.setter
    def relevance(self, relevance):
        """Sets the relevance of this ContentAllOf.


        :param relevance: The relevance of this ContentAllOf.  # noqa: E501
        :type: float
        """
        if relevance is None:
            raise ValueError("Invalid value for `relevance`, must not be `None`")  # noqa: E501

        self._relevance = relevance

    @property
    def role_type(self):
        """Gets the role_type of this ContentAllOf.  # noqa: E501


        :return: The role_type of this ContentAllOf.  # noqa: E501
        :rtype: str
        """
        return self._role_type

    @role_type.setter
    def role_type(self, role_type):
        """Sets the role_type of this ContentAllOf.


        :param role_type: The role_type of this ContentAllOf.  # noqa: E501
        :type: str
        """

        self._role_type = role_type

    @property
    def search_rank(self):
        """Gets the search_rank of this ContentAllOf.  # noqa: E501


        :return: The search_rank of this ContentAllOf.  # noqa: E501
        :rtype: float
        """
        return self._search_rank

    @search_rank.setter
    def search_rank(self, search_rank):
        """Sets the search_rank of this ContentAllOf.


        :param search_rank: The search_rank of this ContentAllOf.  # noqa: E501
        :type: float
        """
        if search_rank is None:
            raise ValueError("Invalid value for `search_rank`, must not be `None`")  # noqa: E501

        self._search_rank = search_rank

    @property
    def travis_status_url(self):
        """Gets the travis_status_url of this ContentAllOf.  # noqa: E501


        :return: The travis_status_url of this ContentAllOf.  # noqa: E501
        :rtype: str
        """
        return self._travis_status_url

    @travis_status_url.setter
    def travis_status_url(self, travis_status_url):
        """Sets the travis_status_url of this ContentAllOf.


        :param travis_status_url: The travis_status_url of this ContentAllOf.  # noqa: E501
        :type: str
        """

        self._travis_status_url = travis_status_url

    @property
    def username(self):
        """Gets the username of this ContentAllOf.  # noqa: E501


        :return: The username of this ContentAllOf.  # noqa: E501
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username):
        """Sets the username of this ContentAllOf.


        :param username: The username of this ContentAllOf.  # noqa: E501
        :type: str
        """

        self._username = username

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ContentAllOf):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
