# coding: utf-8

"""
    Galaxy 3.2 API (wip)

    Galaxy 3.2 API (wip)  # noqa: E501

    The version of the OpenAPI document: 1.1.1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class InlineResponse20015Error(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'code': 'str',
        'description': 'str',
        'traceback': 'str'
    }

    attribute_map = {
        'code': 'code',
        'description': 'description',
        'traceback': 'traceback'
    }

    def __init__(self, code=None, description=None, traceback=None):  # noqa: E501
        """InlineResponse20015Error - a model defined in OpenAPI"""  # noqa: E501

        self._code = None
        self._description = None
        self._traceback = None
        self.discriminator = None

        if code is not None:
            self.code = code
        if description is not None:
            self.description = description
        if traceback is not None:
            self.traceback = traceback

    @property
    def code(self):
        """Gets the code of this InlineResponse20015Error.  # noqa: E501


        :return: The code of this InlineResponse20015Error.  # noqa: E501
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code):
        """Sets the code of this InlineResponse20015Error.


        :param code: The code of this InlineResponse20015Error.  # noqa: E501
        :type: str
        """

        self._code = code

    @property
    def description(self):
        """Gets the description of this InlineResponse20015Error.  # noqa: E501


        :return: The description of this InlineResponse20015Error.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this InlineResponse20015Error.


        :param description: The description of this InlineResponse20015Error.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def traceback(self):
        """Gets the traceback of this InlineResponse20015Error.  # noqa: E501


        :return: The traceback of this InlineResponse20015Error.  # noqa: E501
        :rtype: str
        """
        return self._traceback

    @traceback.setter
    def traceback(self, traceback):
        """Sets the traceback of this InlineResponse20015Error.


        :param traceback: The traceback of this InlineResponse20015Error.  # noqa: E501
        :type: str
        """

        self._traceback = traceback

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse20015Error):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
