# coding: utf-8

"""
    Galaxy 3.2 API (wip)

    Galaxy 3.2 API (wip)  # noqa: E501

    The version of the OpenAPI document: 1.1.1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class InlineResponse20015(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'error': 'InlineResponse20015Error',
        'finished_at': 'datetime',
        'id': 'int',
        'imported_version': 'str',
        'job_id': 'str',
        'lint_records': 'object',
        'messages': 'list[InlineResponse20015Messages]',
        'name': 'str',
        'namespace': 'str',
        'started_at': 'datetime',
        'state': 'str',
        'version': 'str'
    }

    attribute_map = {
        'error': 'error',
        'finished_at': 'finished_at',
        'id': 'id',
        'imported_version': 'imported_version',
        'job_id': 'job_id',
        'lint_records': 'lint_records',
        'messages': 'messages',
        'name': 'name',
        'namespace': 'namespace',
        'started_at': 'started_at',
        'state': 'state',
        'version': 'version'
    }

    def __init__(self, error=None, finished_at=None, id=None, imported_version=None, job_id=None, lint_records=None, messages=None, name=None, namespace=None, started_at=None, state=None, version=None):  # noqa: E501
        """InlineResponse20015 - a model defined in OpenAPI"""  # noqa: E501

        self._error = None
        self._finished_at = None
        self._id = None
        self._imported_version = None
        self._job_id = None
        self._lint_records = None
        self._messages = None
        self._name = None
        self._namespace = None
        self._started_at = None
        self._state = None
        self._version = None
        self.discriminator = None

        self.error = error
        self.finished_at = finished_at
        self.id = id
        if imported_version is not None:
            self.imported_version = imported_version
        self.job_id = job_id
        self.lint_records = lint_records
        self.messages = messages
        self.name = name
        self.namespace = namespace
        self.started_at = started_at
        self.state = state
        self.version = version

    @property
    def error(self):
        """Gets the error of this InlineResponse20015.  # noqa: E501


        :return: The error of this InlineResponse20015.  # noqa: E501
        :rtype: InlineResponse20015Error
        """
        return self._error

    @error.setter
    def error(self, error):
        """Sets the error of this InlineResponse20015.


        :param error: The error of this InlineResponse20015.  # noqa: E501
        :type: InlineResponse20015Error
        """
        if error is None:
            raise ValueError("Invalid value for `error`, must not be `None`")  # noqa: E501

        self._error = error

    @property
    def finished_at(self):
        """Gets the finished_at of this InlineResponse20015.  # noqa: E501


        :return: The finished_at of this InlineResponse20015.  # noqa: E501
        :rtype: datetime
        """
        return self._finished_at

    @finished_at.setter
    def finished_at(self, finished_at):
        """Sets the finished_at of this InlineResponse20015.


        :param finished_at: The finished_at of this InlineResponse20015.  # noqa: E501
        :type: datetime
        """
        if finished_at is None:
            raise ValueError("Invalid value for `finished_at`, must not be `None`")  # noqa: E501

        self._finished_at = finished_at

    @property
    def id(self):
        """Gets the id of this InlineResponse20015.  # noqa: E501


        :return: The id of this InlineResponse20015.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this InlineResponse20015.


        :param id: The id of this InlineResponse20015.  # noqa: E501
        :type: int
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def imported_version(self):
        """Gets the imported_version of this InlineResponse20015.  # noqa: E501


        :return: The imported_version of this InlineResponse20015.  # noqa: E501
        :rtype: str
        """
        return self._imported_version

    @imported_version.setter
    def imported_version(self, imported_version):
        """Sets the imported_version of this InlineResponse20015.


        :param imported_version: The imported_version of this InlineResponse20015.  # noqa: E501
        :type: str
        """

        self._imported_version = imported_version

    @property
    def job_id(self):
        """Gets the job_id of this InlineResponse20015.  # noqa: E501


        :return: The job_id of this InlineResponse20015.  # noqa: E501
        :rtype: str
        """
        return self._job_id

    @job_id.setter
    def job_id(self, job_id):
        """Sets the job_id of this InlineResponse20015.


        :param job_id: The job_id of this InlineResponse20015.  # noqa: E501
        :type: str
        """
        if job_id is None:
            raise ValueError("Invalid value for `job_id`, must not be `None`")  # noqa: E501

        self._job_id = job_id

    @property
    def lint_records(self):
        """Gets the lint_records of this InlineResponse20015.  # noqa: E501


        :return: The lint_records of this InlineResponse20015.  # noqa: E501
        :rtype: object
        """
        return self._lint_records

    @lint_records.setter
    def lint_records(self, lint_records):
        """Sets the lint_records of this InlineResponse20015.


        :param lint_records: The lint_records of this InlineResponse20015.  # noqa: E501
        :type: object
        """
        if lint_records is None:
            raise ValueError("Invalid value for `lint_records`, must not be `None`")  # noqa: E501

        self._lint_records = lint_records

    @property
    def messages(self):
        """Gets the messages of this InlineResponse20015.  # noqa: E501


        :return: The messages of this InlineResponse20015.  # noqa: E501
        :rtype: list[InlineResponse20015Messages]
        """
        return self._messages

    @messages.setter
    def messages(self, messages):
        """Sets the messages of this InlineResponse20015.


        :param messages: The messages of this InlineResponse20015.  # noqa: E501
        :type: list[InlineResponse20015Messages]
        """
        if messages is None:
            raise ValueError("Invalid value for `messages`, must not be `None`")  # noqa: E501

        self._messages = messages

    @property
    def name(self):
        """Gets the name of this InlineResponse20015.  # noqa: E501


        :return: The name of this InlineResponse20015.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this InlineResponse20015.


        :param name: The name of this InlineResponse20015.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501
        if name is not None and len(name) > 64:
            raise ValueError("Invalid value for `name`, length must be less than or equal to `64`")  # noqa: E501

        self._name = name

    @property
    def namespace(self):
        """Gets the namespace of this InlineResponse20015.  # noqa: E501


        :return: The namespace of this InlineResponse20015.  # noqa: E501
        :rtype: str
        """
        return self._namespace

    @namespace.setter
    def namespace(self, namespace):
        """Sets the namespace of this InlineResponse20015.


        :param namespace: The namespace of this InlineResponse20015.  # noqa: E501
        :type: str
        """
        if namespace is None:
            raise ValueError("Invalid value for `namespace`, must not be `None`")  # noqa: E501

        self._namespace = namespace

    @property
    def started_at(self):
        """Gets the started_at of this InlineResponse20015.  # noqa: E501


        :return: The started_at of this InlineResponse20015.  # noqa: E501
        :rtype: datetime
        """
        return self._started_at

    @started_at.setter
    def started_at(self, started_at):
        """Sets the started_at of this InlineResponse20015.


        :param started_at: The started_at of this InlineResponse20015.  # noqa: E501
        :type: datetime
        """
        if started_at is None:
            raise ValueError("Invalid value for `started_at`, must not be `None`")  # noqa: E501

        self._started_at = started_at

    @property
    def state(self):
        """Gets the state of this InlineResponse20015.  # noqa: E501


        :return: The state of this InlineResponse20015.  # noqa: E501
        :rtype: str
        """
        return self._state

    @state.setter
    def state(self, state):
        """Sets the state of this InlineResponse20015.


        :param state: The state of this InlineResponse20015.  # noqa: E501
        :type: str
        """
        if state is None:
            raise ValueError("Invalid value for `state`, must not be `None`")  # noqa: E501

        self._state = state

    @property
    def version(self):
        """Gets the version of this InlineResponse20015.  # noqa: E501


        :return: The version of this InlineResponse20015.  # noqa: E501
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version):
        """Sets the version of this InlineResponse20015.


        :param version: The version of this InlineResponse20015.  # noqa: E501
        :type: str
        """
        if version is None:
            raise ValueError("Invalid value for `version`, must not be `None`")  # noqa: E501
        if version is not None and len(version) > 64:
            raise ValueError("Invalid value for `version`, length must be less than or equal to `64`")  # noqa: E501

        self._version = version

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse20015):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
