# coding: utf-8

"""
    Galaxy 3.2 API (wip)

    Galaxy 3.2 API (wip)  # noqa: E501

    The version of the OpenAPI document: 1.1.1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class InlineResponse20014(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'active': 'str',
        'created': 'str',
        'github_repo': 'str',
        'github_user': 'str',
        'modified': 'str',
        'owner': 'str',
        'related': 'str',
        'summary_fields': 'str',
        'url': 'str'
    }

    attribute_map = {
        'active': 'active',
        'created': 'created',
        'github_repo': 'github_repo',
        'github_user': 'github_user',
        'modified': 'modified',
        'owner': 'owner',
        'related': 'related',
        'summary_fields': 'summary_fields',
        'url': 'url'
    }

    def __init__(self, active=None, created=None, github_repo=None, github_user=None, modified=None, owner=None, related=None, summary_fields=None, url=None):  # noqa: E501
        """InlineResponse20014 - a model defined in OpenAPI"""  # noqa: E501

        self._active = None
        self._created = None
        self._github_repo = None
        self._github_user = None
        self._modified = None
        self._owner = None
        self._related = None
        self._summary_fields = None
        self._url = None
        self.discriminator = None

        if active is not None:
            self.active = active
        if created is not None:
            self.created = created
        self.github_repo = github_repo
        self.github_user = github_user
        if modified is not None:
            self.modified = modified
        if owner is not None:
            self.owner = owner
        if related is not None:
            self.related = related
        if summary_fields is not None:
            self.summary_fields = summary_fields
        if url is not None:
            self.url = url

    @property
    def active(self):
        """Gets the active of this InlineResponse20014.  # noqa: E501


        :return: The active of this InlineResponse20014.  # noqa: E501
        :rtype: str
        """
        return self._active

    @active.setter
    def active(self, active):
        """Sets the active of this InlineResponse20014.


        :param active: The active of this InlineResponse20014.  # noqa: E501
        :type: str
        """

        self._active = active

    @property
    def created(self):
        """Gets the created of this InlineResponse20014.  # noqa: E501

        Timestamp when this subscription was created.  # noqa: E501

        :return: The created of this InlineResponse20014.  # noqa: E501
        :rtype: str
        """
        return self._created

    @created.setter
    def created(self, created):
        """Sets the created of this InlineResponse20014.

        Timestamp when this subscription was created.  # noqa: E501

        :param created: The created of this InlineResponse20014.  # noqa: E501
        :type: str
        """

        self._created = created

    @property
    def github_repo(self):
        """Gets the github_repo of this InlineResponse20014.  # noqa: E501


        :return: The github_repo of this InlineResponse20014.  # noqa: E501
        :rtype: str
        """
        return self._github_repo

    @github_repo.setter
    def github_repo(self, github_repo):
        """Sets the github_repo of this InlineResponse20014.


        :param github_repo: The github_repo of this InlineResponse20014.  # noqa: E501
        :type: str
        """
        if github_repo is None:
            raise ValueError("Invalid value for `github_repo`, must not be `None`")  # noqa: E501
        if github_repo is not None and len(github_repo) > 256:
            raise ValueError("Invalid value for `github_repo`, length must be less than or equal to `256`")  # noqa: E501

        self._github_repo = github_repo

    @property
    def github_user(self):
        """Gets the github_user of this InlineResponse20014.  # noqa: E501


        :return: The github_user of this InlineResponse20014.  # noqa: E501
        :rtype: str
        """
        return self._github_user

    @github_user.setter
    def github_user(self, github_user):
        """Sets the github_user of this InlineResponse20014.


        :param github_user: The github_user of this InlineResponse20014.  # noqa: E501
        :type: str
        """
        if github_user is None:
            raise ValueError("Invalid value for `github_user`, must not be `None`")  # noqa: E501
        if github_user is not None and len(github_user) > 256:
            raise ValueError("Invalid value for `github_user`, length must be less than or equal to `256`")  # noqa: E501

        self._github_user = github_user

    @property
    def modified(self):
        """Gets the modified of this InlineResponse20014.  # noqa: E501

        Timestamp when this subscription was last modified.  # noqa: E501

        :return: The modified of this InlineResponse20014.  # noqa: E501
        :rtype: str
        """
        return self._modified

    @modified.setter
    def modified(self, modified):
        """Sets the modified of this InlineResponse20014.

        Timestamp when this subscription was last modified.  # noqa: E501

        :param modified: The modified of this InlineResponse20014.  # noqa: E501
        :type: str
        """

        self._modified = modified

    @property
    def owner(self):
        """Gets the owner of this InlineResponse20014.  # noqa: E501


        :return: The owner of this InlineResponse20014.  # noqa: E501
        :rtype: str
        """
        return self._owner

    @owner.setter
    def owner(self, owner):
        """Sets the owner of this InlineResponse20014.


        :param owner: The owner of this InlineResponse20014.  # noqa: E501
        :type: str
        """

        self._owner = owner

    @property
    def related(self):
        """Gets the related of this InlineResponse20014.  # noqa: E501

        Data structure with URLs of related resources.  # noqa: E501

        :return: The related of this InlineResponse20014.  # noqa: E501
        :rtype: str
        """
        return self._related

    @related.setter
    def related(self, related):
        """Sets the related of this InlineResponse20014.

        Data structure with URLs of related resources.  # noqa: E501

        :param related: The related of this InlineResponse20014.  # noqa: E501
        :type: str
        """

        self._related = related

    @property
    def summary_fields(self):
        """Gets the summary_fields of this InlineResponse20014.  # noqa: E501

        Data structure with name/description for related resources.  # noqa: E501

        :return: The summary_fields of this InlineResponse20014.  # noqa: E501
        :rtype: str
        """
        return self._summary_fields

    @summary_fields.setter
    def summary_fields(self, summary_fields):
        """Sets the summary_fields of this InlineResponse20014.

        Data structure with name/description for related resources.  # noqa: E501

        :param summary_fields: The summary_fields of this InlineResponse20014.  # noqa: E501
        :type: str
        """

        self._summary_fields = summary_fields

    @property
    def url(self):
        """Gets the url of this InlineResponse20014.  # noqa: E501

        URL for this subscription.  # noqa: E501

        :return: The url of this InlineResponse20014.  # noqa: E501
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this InlineResponse20014.

        URL for this subscription.  # noqa: E501

        :param url: The url of this InlineResponse20014.  # noqa: E501
        :type: str
        """

        self._url = url

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse20014):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
