# coding: utf-8

"""
    Galaxy 3.2 API (wip)

    Galaxy 3.2 API (wip)  # noqa: E501

    The version of the OpenAPI document: 1.1.1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class InlineResponse200(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'active': 'str',
        'collection': 'str',
        'created': 'str',
        'id': 'int',
        'message': 'str',
        'modified': 'str',
        'related': 'str',
        'repository': 'str',
        'seen': 'bool',
        'summary_fields': 'str',
        'type': 'str',
        'url': 'str'
    }

    attribute_map = {
        'active': 'active',
        'collection': 'collection',
        'created': 'created',
        'id': 'id',
        'message': 'message',
        'modified': 'modified',
        'related': 'related',
        'repository': 'repository',
        'seen': 'seen',
        'summary_fields': 'summary_fields',
        'type': 'type',
        'url': 'url'
    }

    def __init__(self, active=None, collection=None, created=None, id=None, message=None, modified=None, related=None, repository=None, seen=None, summary_fields=None, type=None, url=None):  # noqa: E501
        """InlineResponse200 - a model defined in OpenAPI"""  # noqa: E501

        self._active = None
        self._collection = None
        self._created = None
        self._id = None
        self._message = None
        self._modified = None
        self._related = None
        self._repository = None
        self._seen = None
        self._summary_fields = None
        self._type = None
        self._url = None
        self.discriminator = None

        if active is not None:
            self.active = active
        if collection is not None:
            self.collection = collection
        if created is not None:
            self.created = created
        if id is not None:
            self.id = id
        if message is not None:
            self.message = message
        if modified is not None:
            self.modified = modified
        if related is not None:
            self.related = related
        if repository is not None:
            self.repository = repository
        if seen is not None:
            self.seen = seen
        if summary_fields is not None:
            self.summary_fields = summary_fields
        if type is not None:
            self.type = type
        if url is not None:
            self.url = url

    @property
    def active(self):
        """Gets the active of this InlineResponse200.  # noqa: E501


        :return: The active of this InlineResponse200.  # noqa: E501
        :rtype: str
        """
        return self._active

    @active.setter
    def active(self, active):
        """Sets the active of this InlineResponse200.


        :param active: The active of this InlineResponse200.  # noqa: E501
        :type: str
        """

        self._active = active

    @property
    def collection(self):
        """Gets the collection of this InlineResponse200.  # noqa: E501


        :return: The collection of this InlineResponse200.  # noqa: E501
        :rtype: str
        """
        return self._collection

    @collection.setter
    def collection(self, collection):
        """Sets the collection of this InlineResponse200.


        :param collection: The collection of this InlineResponse200.  # noqa: E501
        :type: str
        """

        self._collection = collection

    @property
    def created(self):
        """Gets the created of this InlineResponse200.  # noqa: E501

        Timestamp when this user notification was created.  # noqa: E501

        :return: The created of this InlineResponse200.  # noqa: E501
        :rtype: str
        """
        return self._created

    @created.setter
    def created(self, created):
        """Sets the created of this InlineResponse200.

        Timestamp when this user notification was created.  # noqa: E501

        :param created: The created of this InlineResponse200.  # noqa: E501
        :type: str
        """

        self._created = created

    @property
    def id(self):
        """Gets the id of this InlineResponse200.  # noqa: E501

        Database ID for this user notification.  # noqa: E501

        :return: The id of this InlineResponse200.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this InlineResponse200.

        Database ID for this user notification.  # noqa: E501

        :param id: The id of this InlineResponse200.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def message(self):
        """Gets the message of this InlineResponse200.  # noqa: E501


        :return: The message of this InlineResponse200.  # noqa: E501
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this InlineResponse200.


        :param message: The message of this InlineResponse200.  # noqa: E501
        :type: str
        """

        self._message = message

    @property
    def modified(self):
        """Gets the modified of this InlineResponse200.  # noqa: E501

        Timestamp when this user notification was last modified.  # noqa: E501

        :return: The modified of this InlineResponse200.  # noqa: E501
        :rtype: str
        """
        return self._modified

    @modified.setter
    def modified(self, modified):
        """Sets the modified of this InlineResponse200.

        Timestamp when this user notification was last modified.  # noqa: E501

        :param modified: The modified of this InlineResponse200.  # noqa: E501
        :type: str
        """

        self._modified = modified

    @property
    def related(self):
        """Gets the related of this InlineResponse200.  # noqa: E501

        Data structure with URLs of related resources.  # noqa: E501

        :return: The related of this InlineResponse200.  # noqa: E501
        :rtype: str
        """
        return self._related

    @related.setter
    def related(self, related):
        """Sets the related of this InlineResponse200.

        Data structure with URLs of related resources.  # noqa: E501

        :param related: The related of this InlineResponse200.  # noqa: E501
        :type: str
        """

        self._related = related

    @property
    def repository(self):
        """Gets the repository of this InlineResponse200.  # noqa: E501


        :return: The repository of this InlineResponse200.  # noqa: E501
        :rtype: str
        """
        return self._repository

    @repository.setter
    def repository(self, repository):
        """Sets the repository of this InlineResponse200.


        :param repository: The repository of this InlineResponse200.  # noqa: E501
        :type: str
        """

        self._repository = repository

    @property
    def seen(self):
        """Gets the seen of this InlineResponse200.  # noqa: E501


        :return: The seen of this InlineResponse200.  # noqa: E501
        :rtype: bool
        """
        return self._seen

    @seen.setter
    def seen(self, seen):
        """Sets the seen of this InlineResponse200.


        :param seen: The seen of this InlineResponse200.  # noqa: E501
        :type: bool
        """

        self._seen = seen

    @property
    def summary_fields(self):
        """Gets the summary_fields of this InlineResponse200.  # noqa: E501

        Data structure with name/description for related resources.  # noqa: E501

        :return: The summary_fields of this InlineResponse200.  # noqa: E501
        :rtype: str
        """
        return self._summary_fields

    @summary_fields.setter
    def summary_fields(self, summary_fields):
        """Sets the summary_fields of this InlineResponse200.

        Data structure with name/description for related resources.  # noqa: E501

        :param summary_fields: The summary_fields of this InlineResponse200.  # noqa: E501
        :type: str
        """

        self._summary_fields = summary_fields

    @property
    def type(self):
        """Gets the type of this InlineResponse200.  # noqa: E501


        :return: The type of this InlineResponse200.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this InlineResponse200.


        :param type: The type of this InlineResponse200.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def url(self):
        """Gets the url of this InlineResponse200.  # noqa: E501

        URL for this user notification.  # noqa: E501

        :return: The url of this InlineResponse200.  # noqa: E501
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this InlineResponse200.

        URL for this user notification.  # noqa: E501

        :param url: The url of this InlineResponse200.  # noqa: E501
        :type: str
        """

        self._url = url

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse200):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
