# coding: utf-8

"""
    Galaxy 3.2 API (wip)

    Galaxy 3.2 API (wip)  # noqa: E501

    The version of the OpenAPI document: 1.1.1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class InlineResponse2002(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'community_score': 'float',
        'community_survey_count': 'int',
        'created': 'datetime',
        'deprecated': 'bool',
        'download_count': 'int',
        'id': 'int',
        'latest_version': 'InlineResponse2002LatestVersion',
        'modified': 'datetime',
        'name': 'str',
        'namespace': 'InlineResponse2002Namespace'
    }

    attribute_map = {
        'community_score': 'community_score',
        'community_survey_count': 'community_survey_count',
        'created': 'created',
        'deprecated': 'deprecated',
        'download_count': 'download_count',
        'id': 'id',
        'latest_version': 'latest_version',
        'modified': 'modified',
        'name': 'name',
        'namespace': 'namespace'
    }

    def __init__(self, community_score=None, community_survey_count=None, created=None, deprecated=None, download_count=None, id=None, latest_version=None, modified=None, name=None, namespace=None):  # noqa: E501
        """InlineResponse2002 - a model defined in OpenAPI"""  # noqa: E501

        self._community_score = None
        self._community_survey_count = None
        self._created = None
        self._deprecated = None
        self._download_count = None
        self._id = None
        self._latest_version = None
        self._modified = None
        self._name = None
        self._namespace = None
        self.discriminator = None

        self.community_score = community_score
        if community_survey_count is not None:
            self.community_survey_count = community_survey_count
        if created is not None:
            self.created = created
        if deprecated is not None:
            self.deprecated = deprecated
        if download_count is not None:
            self.download_count = download_count
        if id is not None:
            self.id = id
        self.latest_version = latest_version
        if modified is not None:
            self.modified = modified
        self.name = name
        if namespace is not None:
            self.namespace = namespace

    @property
    def community_score(self):
        """Gets the community_score of this InlineResponse2002.  # noqa: E501


        :return: The community_score of this InlineResponse2002.  # noqa: E501
        :rtype: float
        """
        return self._community_score

    @community_score.setter
    def community_score(self, community_score):
        """Sets the community_score of this InlineResponse2002.


        :param community_score: The community_score of this InlineResponse2002.  # noqa: E501
        :type: float
        """

        self._community_score = community_score

    @property
    def community_survey_count(self):
        """Gets the community_survey_count of this InlineResponse2002.  # noqa: E501


        :return: The community_survey_count of this InlineResponse2002.  # noqa: E501
        :rtype: int
        """
        return self._community_survey_count

    @community_survey_count.setter
    def community_survey_count(self, community_survey_count):
        """Sets the community_survey_count of this InlineResponse2002.


        :param community_survey_count: The community_survey_count of this InlineResponse2002.  # noqa: E501
        :type: int
        """
        if community_survey_count is not None and community_survey_count > 2147483647:  # noqa: E501
            raise ValueError("Invalid value for `community_survey_count`, must be a value less than or equal to `2147483647`")  # noqa: E501
        if community_survey_count is not None and community_survey_count < -2147483648:  # noqa: E501
            raise ValueError("Invalid value for `community_survey_count`, must be a value greater than or equal to `-2147483648`")  # noqa: E501

        self._community_survey_count = community_survey_count

    @property
    def created(self):
        """Gets the created of this InlineResponse2002.  # noqa: E501


        :return: The created of this InlineResponse2002.  # noqa: E501
        :rtype: datetime
        """
        return self._created

    @created.setter
    def created(self, created):
        """Sets the created of this InlineResponse2002.


        :param created: The created of this InlineResponse2002.  # noqa: E501
        :type: datetime
        """

        self._created = created

    @property
    def deprecated(self):
        """Gets the deprecated of this InlineResponse2002.  # noqa: E501


        :return: The deprecated of this InlineResponse2002.  # noqa: E501
        :rtype: bool
        """
        return self._deprecated

    @deprecated.setter
    def deprecated(self, deprecated):
        """Sets the deprecated of this InlineResponse2002.


        :param deprecated: The deprecated of this InlineResponse2002.  # noqa: E501
        :type: bool
        """

        self._deprecated = deprecated

    @property
    def download_count(self):
        """Gets the download_count of this InlineResponse2002.  # noqa: E501


        :return: The download_count of this InlineResponse2002.  # noqa: E501
        :rtype: int
        """
        return self._download_count

    @download_count.setter
    def download_count(self, download_count):
        """Sets the download_count of this InlineResponse2002.


        :param download_count: The download_count of this InlineResponse2002.  # noqa: E501
        :type: int
        """
        if download_count is not None and download_count > 2147483647:  # noqa: E501
            raise ValueError("Invalid value for `download_count`, must be a value less than or equal to `2147483647`")  # noqa: E501
        if download_count is not None and download_count < -2147483648:  # noqa: E501
            raise ValueError("Invalid value for `download_count`, must be a value greater than or equal to `-2147483648`")  # noqa: E501

        self._download_count = download_count

    @property
    def id(self):
        """Gets the id of this InlineResponse2002.  # noqa: E501


        :return: The id of this InlineResponse2002.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this InlineResponse2002.


        :param id: The id of this InlineResponse2002.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def latest_version(self):
        """Gets the latest_version of this InlineResponse2002.  # noqa: E501


        :return: The latest_version of this InlineResponse2002.  # noqa: E501
        :rtype: InlineResponse2002LatestVersion
        """
        return self._latest_version

    @latest_version.setter
    def latest_version(self, latest_version):
        """Sets the latest_version of this InlineResponse2002.


        :param latest_version: The latest_version of this InlineResponse2002.  # noqa: E501
        :type: InlineResponse2002LatestVersion
        """
        if latest_version is None:
            raise ValueError("Invalid value for `latest_version`, must not be `None`")  # noqa: E501

        self._latest_version = latest_version

    @property
    def modified(self):
        """Gets the modified of this InlineResponse2002.  # noqa: E501


        :return: The modified of this InlineResponse2002.  # noqa: E501
        :rtype: datetime
        """
        return self._modified

    @modified.setter
    def modified(self, modified):
        """Sets the modified of this InlineResponse2002.


        :param modified: The modified of this InlineResponse2002.  # noqa: E501
        :type: datetime
        """

        self._modified = modified

    @property
    def name(self):
        """Gets the name of this InlineResponse2002.  # noqa: E501


        :return: The name of this InlineResponse2002.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this InlineResponse2002.


        :param name: The name of this InlineResponse2002.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501
        if name is not None and len(name) > 64:
            raise ValueError("Invalid value for `name`, length must be less than or equal to `64`")  # noqa: E501

        self._name = name

    @property
    def namespace(self):
        """Gets the namespace of this InlineResponse2002.  # noqa: E501


        :return: The namespace of this InlineResponse2002.  # noqa: E501
        :rtype: InlineResponse2002Namespace
        """
        return self._namespace

    @namespace.setter
    def namespace(self, namespace):
        """Sets the namespace of this InlineResponse2002.


        :param namespace: The namespace of this InlineResponse2002.  # noqa: E501
        :type: InlineResponse2002Namespace
        """

        self._namespace = namespace

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse2002):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
