# coding: utf-8

"""
    Galaxy 3.2 API (wip)

    Galaxy 3.2 API (wip)  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class NamespaceAllOf(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'avatar_url': 'str',
        'company': 'str',
        'description': 'str',
        'email': 'str',
        'html_url': 'str',
        'is_vendor': 'bool',
        'location': 'str',
        'name': 'str'
    }

    attribute_map = {
        'avatar_url': 'avatar_url',
        'company': 'company',
        'description': 'description',
        'email': 'email',
        'html_url': 'html_url',
        'is_vendor': 'is_vendor',
        'location': 'location',
        'name': 'name'
    }

    def __init__(self, avatar_url=None, company=None, description=None, email=None, html_url=None, is_vendor=None, location=None, name=None):  # noqa: E501
        """NamespaceAllOf - a model defined in OpenAPI"""  # noqa: E501

        self._avatar_url = None
        self._company = None
        self._description = None
        self._email = None
        self._html_url = None
        self._is_vendor = None
        self._location = None
        self._name = None
        self.discriminator = None

        self.avatar_url = avatar_url
        self.company = company
        if description is not None:
            self.description = description
        self.email = email
        self.html_url = html_url
        if is_vendor is not None:
            self.is_vendor = is_vendor
        self.location = location
        self.name = name

    @property
    def avatar_url(self):
        """Gets the avatar_url of this NamespaceAllOf.  # noqa: E501


        :return: The avatar_url of this NamespaceAllOf.  # noqa: E501
        :rtype: str
        """
        return self._avatar_url

    @avatar_url.setter
    def avatar_url(self, avatar_url):
        """Sets the avatar_url of this NamespaceAllOf.


        :param avatar_url: The avatar_url of this NamespaceAllOf.  # noqa: E501
        :type: str
        """
        if avatar_url is not None and len(avatar_url) > 256:
            raise ValueError("Invalid value for `avatar_url`, length must be less than or equal to `256`")  # noqa: E501

        self._avatar_url = avatar_url

    @property
    def company(self):
        """Gets the company of this NamespaceAllOf.  # noqa: E501


        :return: The company of this NamespaceAllOf.  # noqa: E501
        :rtype: str
        """
        return self._company

    @company.setter
    def company(self, company):
        """Sets the company of this NamespaceAllOf.


        :param company: The company of this NamespaceAllOf.  # noqa: E501
        :type: str
        """
        if company is not None and len(company) > 256:
            raise ValueError("Invalid value for `company`, length must be less than or equal to `256`")  # noqa: E501

        self._company = company

    @property
    def description(self):
        """Gets the description of this NamespaceAllOf.  # noqa: E501


        :return: The description of this NamespaceAllOf.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this NamespaceAllOf.


        :param description: The description of this NamespaceAllOf.  # noqa: E501
        :type: str
        """
        if description is not None and len(description) > 255:
            raise ValueError("Invalid value for `description`, length must be less than or equal to `255`")  # noqa: E501

        self._description = description

    @property
    def email(self):
        """Gets the email of this NamespaceAllOf.  # noqa: E501


        :return: The email of this NamespaceAllOf.  # noqa: E501
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this NamespaceAllOf.


        :param email: The email of this NamespaceAllOf.  # noqa: E501
        :type: str
        """
        if email is not None and len(email) > 256:
            raise ValueError("Invalid value for `email`, length must be less than or equal to `256`")  # noqa: E501

        self._email = email

    @property
    def html_url(self):
        """Gets the html_url of this NamespaceAllOf.  # noqa: E501


        :return: The html_url of this NamespaceAllOf.  # noqa: E501
        :rtype: str
        """
        return self._html_url

    @html_url.setter
    def html_url(self, html_url):
        """Sets the html_url of this NamespaceAllOf.


        :param html_url: The html_url of this NamespaceAllOf.  # noqa: E501
        :type: str
        """
        if html_url is not None and len(html_url) > 256:
            raise ValueError("Invalid value for `html_url`, length must be less than or equal to `256`")  # noqa: E501

        self._html_url = html_url

    @property
    def is_vendor(self):
        """Gets the is_vendor of this NamespaceAllOf.  # noqa: E501


        :return: The is_vendor of this NamespaceAllOf.  # noqa: E501
        :rtype: bool
        """
        return self._is_vendor

    @is_vendor.setter
    def is_vendor(self, is_vendor):
        """Sets the is_vendor of this NamespaceAllOf.


        :param is_vendor: The is_vendor of this NamespaceAllOf.  # noqa: E501
        :type: bool
        """

        self._is_vendor = is_vendor

    @property
    def location(self):
        """Gets the location of this NamespaceAllOf.  # noqa: E501


        :return: The location of this NamespaceAllOf.  # noqa: E501
        :rtype: str
        """
        return self._location

    @location.setter
    def location(self, location):
        """Sets the location of this NamespaceAllOf.


        :param location: The location of this NamespaceAllOf.  # noqa: E501
        :type: str
        """
        if location is not None and len(location) > 256:
            raise ValueError("Invalid value for `location`, length must be less than or equal to `256`")  # noqa: E501

        self._location = location

    @property
    def name(self):
        """Gets the name of this NamespaceAllOf.  # noqa: E501


        :return: The name of this NamespaceAllOf.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this NamespaceAllOf.


        :param name: The name of this NamespaceAllOf.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501
        if name is not None and len(name) > 512:
            raise ValueError("Invalid value for `name`, length must be less than or equal to `512`")  # noqa: E501

        self._name = name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, NamespaceAllOf):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
